name: Deploy to Local Windows Runner

on:
  push:
    branches:
      - main
      - master

env:
  IMAGE_NAME: uuz16/news_analyzer:latest
  CONTAINER_NAME: news_analyzer_container

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Pull latest Docker image
        run: docker pull ${{ env.IMAGE_NAME }}

      - name: Stop existing container
        run: docker stop ${{ env.CONTAINER_NAME }}
        continue-on-error: true

      - name: Remove existing container
        run: docker rm ${{ env.CONTAINER_NAME }}
        continue-on-error: true

      - name: Run new container
        run: docker run -d -p 8000:8000 --name ${{ env.CONTAINER_NAME }} ${{ env.IMAGE_NAME }}
